.TH ROTATE 1 "17 Февр 2016" "Debian GNU/Linux 8.2 (jessie)" "Пользовательские команды"

.SH "НАЗВАНИЕ"
.PP
rotate - поворачивает bmp картинку

.SH "СИНТАКСИС"
.PP
rotate [-r | -l ] [-o result] [-n number] [-h | -?]
.I file

.SH "ОПИСАНИЕ"
.PP
Утилита \fB rotate \fR позволяет поворачивать изображения формата bmp. Можно указать направление поворота (стандартно вправо), количество поворотов, и выходной файл, в который будет записан результат поворота.

.SH "ОПЦИИ"
.PP
Поддерживаются следующие опции
.PP
.TP
\fB-r\fR 
Устанавливает сторону поворота картинки вправо. Является стороной по умолчанию.

.TP
\fB-l\fR 
Устанавливает сторону поворота картинки влево. 

.TP
\fB-n\fR number
Эта опция позволяет повернуть картинку number раз на 90 градусов. Не стоит использовать слишком большое количество поворотов, в таком случае программа может выполняться очень долго. 

.TP
\fB-o\fR 
Позволяет указать выходной файл. По умолчанию - result.bmp

.TP
\fB-h\fR | \fB-?\fR
Выводит справку о команде. На самом деле никакой справки там нет, вам просто предложат посмотреть man страницу.

.SH "ОПЕРАНДЫ"
.PP
.TP
Поддерживаются следующие операнды:
.PP
.TP
.I file
Файл изображения в формате bmp, который необходимо повернуть.
